# Generated by Django 4.0.5 on 2022-06-07 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=20)),
                ('turma', models.OneToOneField(default='Sem Professor', on_delete=django.db.models.deletion.SET_DEFAULT, to='pages.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=10)),
                ('formacao', models.CharField(max_length=20)),
                ('nascimento', models.DateField()),
                ('aluno_do_ifrn', models.BooleanField()),
                ('servidor_do_ifrn', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=15)),
                ('senha', models.CharField(max_length=20)),
                ('turmas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.turma')),
            ],
        ),
    ]
