# Generated by Django 4.0.5 on 2022-06-08 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='email',
            field=models.EmailField(default='desconhecido@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='celular',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(default='desconhecido@email.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='formacao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='genero',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='senha',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turmas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.turma'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='professor',
            name='senha',
            field=models.CharField(max_length=255),
        ),
    ]
