# Generated by Django 4.0.5 on 2022-06-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_professor_email_alter_aluno_celular_alter_aluno_cpf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='aluno_do_ifrn',
            new_name='aluno_ifrn',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='turmas',
        ),
        migrations.AddField(
            model_name='aluno',
            name='instituicao_de_ensino',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
