# Generated by Django 4.0.5 on 2022-06-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_turma_curso_turma_nome_do_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='aprovada',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
    ]
