# Generated by Django 4.0.5 on 2022-06-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_inscricao_aprovada_delete_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='documento',
            field=models.FileField(upload_to='./uploads'),
        ),
    ]
