# Generated by Django 4.0.5 on 2022-06-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_inscricao_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='documento',
            field=models.FileField(upload_to='./uploads/% Y/% m/% d/'),
        ),
    ]
