# Generated by Django 4.0.5 on 2022-06-13 19:56

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_aluno_cpf_alter_inscricao_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='documento',
            field=models.FileField(upload_to=pages.models.caminho_documento),
        ),
    ]
