# Generated by Django 4.0.5 on 2022-09-29 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_falta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('desc', models.TextField(max_length=255)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.turma')),
            ],
        ),
    ]
