# Generated by Django 4.0.5 on 2022-11-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_remove_professor_turma_turma_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='aluno_ifrn',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='email',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='formacao',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='instituicao_de_ensino',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='nascimento',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='servidor_ifrn',
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_inscricao',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='sobrenome',
            field=models.CharField(default='', max_length=9),
        ),
    ]
